### ISSUE TITLE
Add a Dockerfile

### ISSUE THREAD

**Issue by arpit1997** [dellis23/ispy#5]
**Feature Request**
Docker provides a way to run application in a standalone container. So if there is a Docker Image available for this also then it would be great. Docker provides great portability and removes the hassle of dependencies. See if it it is possible. 
Hope to hear back. :smiley:

**Comment by dellis23** [comment]
To be honest, I can't possibly imagine why you'd want to run this in a container :)  You don't want isolation from other processes -- you want to spy on them!  If you can come up with something reasonable and useful feel free to make a PR, but otherwise, I don't mess around with docker enough to see clearly how it would help.
